### ISSUE TITLE
REVAN Crash (segmentation violation)

### ISSUE THREAD

**Issue by mikemoss3** [zoglauer/megalib#44]
Hello,

I don't have much experience with ROOT error messages, so I hope you can help me figure this one out.

When running REVAN I successfully run "Start Event Reconstruction", but when I attempt to use the "Energy spectrum Before/After analysis" in the "Analysis" menu, but I receive an error dealing with memory issues (I believe). I will post the full error message displayed at the end of this post.

This happens for multiple different source/geometry files that I attempt this on.

- Mike Moss

Error Message upon execution: 
```

Warning in <TROOT::Append>: Replacing existing TH1: InitialEnergySpectrum (Potential memory leak).

 *** Break *** segmentation violation



===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x00007f05b6150687 in __GI___waitpid (pid=18927, stat_loc=stat_loc
entry=0x7ffffc6552a8, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f05b60bb067 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007f05b6d4e9ab in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/unix/src/TUnixSystem.cxx:2119
#3  TUnixSystem::StackTrace (this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/unix/src/TUnixSystem.cxx:2413
#4  0x00007f05b6d51394 in TUnixSystem::DispatchSignals (this=0x5627c503c7c0, sig=kSigSegmentationViolation) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/unix/src/TUnixSystem.cxx:3644
#5  <signal handler called>
#6  0x00007f05b831e008 in MInterfaceRevan::EnergyDistribution() () from /home/michael/Documents/MEGAlib/lib/libRevanGui.so
#7  0x00007f05b833e41f in MGUIRevanMain::ProcessMessage(long, long, long) () from /home/michael/Documents/MEGAlib/lib/libRevanGui.so
#8  0x00007f05b5c71be9 in TGFrame::HandleClientMessage (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:657
#9  0x00007f05b5c80911 in TGMainFrame::HandleClientMessage (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:1687
#10 0x00007f05b5c80cbf in TGFrame::HandleEvent (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:533
#11 0x00007f05b5c2cfb8 in TGClient::HandleEvent (this=0x5627c635f170, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:841
#12 0x00007f05b5c2d795 in TGClient::ProcessOneEvent (this=0x5627c635f170) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:651
#13 0x00007f05b5c2d7fa in TGClient::HandleInput (this=0x5627c635f170) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:698
#14 0x00007f05b6d51c68 in TUnixSystem::DispatchOneEvent (this=0x5627c503c7c0, pendingOnly=<optimized out>) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/unix/src/TUnixSystem.cxx:1067
#15 0x00007f05b6c67bc1 in TSystem::InnerLoop (this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TSystem.cxx:411
#16 TSystem::Run (this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TSystem.cxx:361
#17 0x00007f05b6bfa73f in TApplication::Run (this=0x5627c621f600, retrn=<optimized out>) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TApplication.cxx:1173
#18 0x00005627c46ec174 in main ()
===========================================================


The lines below might hint at the cause of the crash.
You may get help by asking at the ROOT forum http://root.cern.ch/forum
Only if you are really convinced it is a bug in ROOT then please submit a
report at http://root.cern.ch/bugs Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x00007f05b831e008 in MInterfaceRevan::EnergyDistribution() () from /home/michael/Documents/MEGAlib/lib/libRevanGui.so
#7  0x00007f05b833e41f in MGUIRevanMain::ProcessMessage(long, long, long) () from /home/michael/Documents/MEGAlib/lib/libRevanGui.so
#8  0x00007f05b5c71be9 in TGFrame::HandleClientMessage (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:657
#9  0x00007f05b5c80911 in TGMainFrame::HandleClientMessage (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:1687
#10 0x00007f05b5c80cbf in TGFrame::HandleEvent (this=0x5627c65b3400, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGFrame.cxx:533
#11 0x00007f05b5c2cfb8 in TGClient::HandleEvent (this=0x5627c635f170, event=0x7ffffc658390) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:841
#12 0x00007f05b5c2d795 in TGClient::ProcessOneEvent (this=0x5627c635f170) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:651
#13 0x00007f05b5c2d7fa in TGClient::HandleInput (this=0x5627c635f170) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/gui/gui/src/TGClient.cxx:698
#14 0x00007f05b6d51c68 in TUnixSystem::DispatchOneEvent (this=0x5627c503c7c0, pendingOnly=<optimized out>) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/unix/src/TUnixSystem.cxx:1067
#15 0x00007f05b6c67bc1 in TSystem::InnerLoop (this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TSystem.cxx:411
#16 TSystem::Run (this=0x5627c503c7c0) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TSystem.cxx:361
#17 0x00007f05b6bfa73f in TApplication::Run (this=0x5627c621f600, retrn=<optimized out>) at /home/michael/Documents/MEGAlib/external/root_v6.14.04/root_v6.14.04-source/core/base/src/TApplication.cxx:1173
#18 0x00005627c46ec174 in main ()
===========================================================

```

**Comment by zoglauer** [comment]
Hi Mike,

Can you email me your geometry, a small sim file which causes the crash, and your revan configuration file? Then I can debug.

Best,
Andreas

**Comment by mikemoss3** [comment]
Ok, I have sent the needed files. 

Best,
Mike

**Comment by zoglauer** [comment]
Fixed.
