### ISSUE TITLE
Crash when closing any MEGAlib application

### ISSUE THREAD

**Issue by zoglauer** [zoglauer/megalib#6]
When closing any MEGAlib application, the application crashes with:

#5  0x00007f13f3ac0ae5 in ?? () from /usr/lib/x86_64-linux-gnu/libXft.so.2
#6  0x00007f13f3abca27 in ?? () from /usr/lib/x86_64-linux-gnu/libXft.so.2
#7  0x00007f13f49484b2 in XCloseDisplay () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f13f4c7f7f0 in TGX11::CloseDisplay (this=0x1542ae0) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/graf2d/x11/src/GX11Gui.cxx:850
#9  0x00007f13fa9d246f in TGClient::~TGClient (this=0x154b570, __in_chrg=<optimized out>) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/gui/gui/src/TGClient.cxx:604
#10 0x00007f13fa9d24c9 in TGClient::~TGClient (this=0x154b570, __in_chrg=<optimized out>) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/gui/gui/src/TGClient.cxx:606
#11 0x00007f13faaa5f64 in TRootApplication::~TRootApplication (this=0x154b530, __in_chrg=<optimized out>) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/gui/gui/src/TRootApplication.cxx:60
#12 0x00007f13faaa5fb9 in TRootApplication::~TRootApplication (this=0x154b530, __in_chrg=<optimized out>) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/gui/gui/src/TRootApplication.cxx:61
#13 0x00007f13fa0caa87 in TApplication::~TApplication (this=0x7ffd24c43480, __in_chrg=<optimized out>) at /home/andreas/Home/Science/Software/External/root_v5.34.34/root_v5.34.34-source/core/base/src/TApplication.cxx:244
#14 0x000000000040162e in main ()

**Comment by zoglauer** [comment]
Solution:
There is some bug involving ROOT and xft.
In your .rootrc file, set 
X11.UseXft:              yes
to
X11.UseXft:              no
And the crash should be gone.
See also: https://sft.its.cern.ch/jira/browse/ROOT-7675
